# This is a basic workflow to help you get started with Actions

name: LaTeX Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install pdflatex
        run: sudo apt install texlive-latex-base
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install readme2tex
      - name: Delete old images
        run: |
          find . -type f -name '*.svg' -delete
      - name: Build readmes
        run: |
          find . -type f -name '*.tex.md' -execdir sh -c 'python3 -m readme2tex --readme $0 --nocdn --output "${0%.tex.md}.md"' {} \;
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [[ `git status --porcelain` ]]; then echo 1; else echo 0; fi)
      - name: Commit the built files
        if: steps.git-check.outputs.modified == 1
        run: |
          git config --global user.name '${{github.repository_owner}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add .
          git commit -am "Built the .tex.md files"
          git push
